x-spark-common: &spark-common
  image: docker.io/bitnamilegacy/spark:3.5.1
  environment:
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
    - SPARK_USER=spark
  volumes:
    - ./spark_events:/tmp/spark-events       # For History Server logs
    - ./datasets:/opt/spark/datasets         # For Raw & Delta Data
    - ./conf:/opt/spark/conf                 # Mount custom configs
    - ./spark_apps:/opt/spark/spark_apps     # To run apps via spark-submit if needed
    - ./conf/metrics.properties:/opt/bitnami/spark/conf/metrics.properties
    - ./conf/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf

services:
  spark-master:
    <<: *spark-common
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080" # Spark Master UI
      - "7077:7077" # Spark Master Port for IDE connection

  spark-worker-1:
    <<: *spark-common
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      #- SPARK_DAEMON_JAVA_OPTS=-Dspark.metrics.conf=/opt/spark/conf/metrics.properties
    depends_on:
      - spark-master

  spark-worker-2:
    <<: *spark-common
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      #- SPARK_DAEMON_JAVA_OPTS=-Dspark.metrics.conf=/opt/spark/conf/metrics.properties
    depends_on:
      - spark-master

  spark-worker-3:
    <<: *spark-common
    container_name: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      #- SPARK_DAEMON_JAVA_OPTS=-Dspark.metrics.conf=/opt/spark/conf/metrics.properties
    depends_on:
      - spark-master

  spark-worker-4:
    <<: *spark-common
    container_name: spark-worker-4
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      #- SPARK_DAEMON_JAVA_OPTS=-Dspark.metrics.conf=/opt/spark/conf/metrics.properties
    depends_on:
      - spark-master

  spark-history-server:
    <<: *spark-common
    container_name: spark-history-server
    environment:
      - SPARK_MODE=master
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=file:/tmp/spark-events
    command: /opt/bitnami/spark/sbin/start-history-server.sh
    ports:
      - "18080:18080" # REST API & History UI
    depends_on:
      - spark-master

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  statsd-exporter:
    image: prom/statsd-exporter:latest
    container_name: statsd-exporter
    ports:
      - "9102:9102"     # The port Prometheus will scrape (HTTP)
      - "9125:9125/udp" # The port Spark will push to (UDP)