# 1. Enable JVM metrics collection (The Source)
*.source.jvm.class=org.apache.spark.metrics.source.JvmSource

# 2. Enable Native StatsD Push (The Sink)
*.sink.statsd.class=org.apache.spark.metrics.sink.StatsdSink
*.sink.statsd.host=statsd-exporter
*.sink.statsd.port=8125

# 3. Add a prefix so we know it came from Spark
*.sink.statsd.prefix=spark